### ISSUE TITLE
Undo move markup control point

### ISSUE THREAD

**Issue by davidneustadter** [Slicer/Slicer#8045] opened 2024-11-13 12:01 UTC
When manipulating the 3D view while displaying unlocked markups (in order to adjust the markup position interactively, for instance), the same left mouse button will rotate the 3D viewing orientation when clicked anywhere other than the markup, and will move the markup or its control points when clicked on the markup or its control points.
I have many times accidentally moved a control point when I intended to rotate the 3D view orientation, and would very much appreciate an "Undo last move" button in order to undo the unintended move.
An even better solution might be to change one of the functions to a different button or to require a keyboard key press together with the button press, etc...

Thanks.

**Comment by lassoan** [comment] 2024-11-14 05:21
This is a duplicate of https://github.com/Slicer/Slicer/issues/4576

We prioritize community feature requests based on votes on the Slicer Forum. This feature has been already requested, so you can vote on it here: https://discourse.slicer.org/t/is-it-possible-to-add-a-global-undo-button/16859/6

**Closed by lassoan** 2024-11-14 05:21 UTC
