### ISSUE TITLE
Exporting DICOM from 3DSlicer

### ISSUE THREAD

**Issue by zaimoh** [Slicer/Slicer#6320] opened 2022-04-19 16:51 UTC
Dear developer,

Good morning, 

I have DICOM set of 84 CT images   with one structure DICOM. When I uploaded them to 3DSlicer, they work. However, after processing the data in 3DSlicer and import them by another software, images can be imported, but structure can not be imported.

Also, I have this message that said I need  ''SlicerRT extension'', but I already installed  ''SlicerRT extension'' 

''Please install SlicerRT extension to enable loading of DICOM RT Structure Set objects''

Is there any suggestion to overcome this issue?

Yours sincerely

**Comment by lassoan** [comment] 2022-04-19 17:06
What software you are trying to load the RTSTRUCT into? Does that software can read RTSTRUCT but not those RTSTRUCTs that Slicer exported?

**Comment by zaimoh** [comment] 2022-04-19 17:50
CERR. Yes, it can

**Comment by lassoan** [comment] 2022-04-19 17:56
CERR is open-source, so you should be able to get detailed information about why it struggles with opening the RTSTRUCT that Slicer exported (too many points in the contour, missing fields, some UID mismatch, etc.). Please send us the details and then based on that we'll see how to proceed.

Please do all testing with the latest Slicer Preview Release (not the latest Slicer Stable Release), because many issues have been fixed since the last stable release and any new fixes and improvements will be added to the preview release.

**Comment by lassoan** [comment] 2022-10-17 04:58
There have been no updates and the issue is most likely a CERR limitation, so I'm closing this.

**Closed by lassoan** 2022-10-17 04:58 UTC
Labels: type:bug
