### ISSUE TITLE
Update extensions for Slicer-4.13

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5269] opened 2020-10-26 20:39 UTC
It is expected that due to VTK and other library updates, extensions may need to be updated, too. This ticket tracks these necessary updates.

Extensions that were considered to be fixed: https://docs.google.com/spreadsheets/d/1GC4DWDpOXhuDYdfYOjJ6PmjHTeMM3-K7SoiC5ZR1GYg/edit?usp=sharing

Extensions that were decided to fix before Slicer5 release:
- [x] Chest_Imaging_Platform ([C++11/14 configuration mismatch](https://github.com/acil-bwh/ChestImagingPlatform/pull/42) + [VTK API change](https://github.com/acil-bwh/SlicerCIP/pull/37))
- [x] SlicerRadiomics (https://discourse.slicer.org/t/slicerradiomics-error/14258, https://discourse.slicer.org/t/factory-build-of-python-extensions-conflicting-with-each-other/21935)
- [x] SlicerVirtualReality (https://github.com/KitwareMedical/SlicerVirtualReality/pull/90)
- [x] ShapePopulationViewer
- [x] ShapeVariationAnalyzer
- [x] SPHARM-PDM
- [x] ukftractography
- [x] ModelToModelDistance
- [x] SlicerVMTK - macOS packaging is broken (https://github.com/vmtk/SlicerExtension-VMTK/issues/37)
- [x] SlicerJupyter - linux build failed, Python and library updates fixed it
- [x] SlicerElastix
- [x] SlicerRT - linux build error due to ITK https://github.com/SlicerRt/SlicerRT/issues/206
- [x] PathReconstruction - linux build fails, probably due to SlicerRT failure
- [x] SegmentRegistration
- [x] CMFreg - Windows build fails
- [x] DCMQI (see https://github.com/QIICR/dcmqi/issues/446)
- [x] Slicer-AirwaySegmentation
- [x] SlicerOpenIGTLink
- [x] SlicerIGSIO (https://github.com/IGSIO/SlicerIGSIO/issues/17)
- [x] SlicerDMRI

**Comment by jamesobutler** [comment] 2021-05-21 02:59
I believe @cpinter also mentioned SlicerVMTK and SlicerVirtualReality as needing updates as it relates to the change to VTK9

**Comment by jamesobutler** [comment] 2021-11-23 16:43
@lassoan I believe SlicerJupyter can be checked off as it appears to be successfully on factory build machines metroplex (Linux), factory-south-macos (macOS) and overload (Windows).

**Comment by jamesobutler** [comment] 2022-02-23 23:22
As it relates to extensions being available from the ExtensionsManager, I brought up https://discourse.slicer.org/t/factory-build-of-python-extensions-conflicting-with-each-other/21935 where it appears the SlicerJupyter build may be causing the SlicerRadiomics build to fail.

**Comment by Sunderlandkyl** [comment] 2022-03-02 20:26
SlicerIGSIO is currently failing on the nightly dashboard (https://slicer.cdash.org/viewBuildError.php?buildid=2609910). (Issue: https://github.com/IGSIO/SlicerIGSIO/issues/17)
```
The specified task executable "rc.exe" could not be run. System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long 
```
I haven't been able to reproduce the problem locally, even with very long paths. @jcfr do you remember if this has come up before, and what was done to fix it?

**Comment by jcfr** [comment] 2022-03-02 20:38
> SlicerIGSIO is currently failing on the nightly dashboard 

Thanks for pointing this out. 

I just connected to the system, open the `SlicerIGSIO.sln`, selected `Release` and initiated the build ... will reported any finding.

**Comment by lassoan** [comment] 2022-03-02 21:21
The best solution would be to pass input arguments to rc.exe via a file instead of command-line arguments, but I'm not sure if rc.exe, Visual Studio project file, and CMake generator all support that.

If that is not available then we could install ITK and VTK. It is obscene that VTK adds about 380 include paths and ITK adds about 180, while they could add just 1 instead. It might greatly speed up compilation on Windows, too, because searching for include files in hundreds of paths on NTFS filesystems takes really long time. By caching include file lookups in the Python wrapper we've managed to speed up Python wrapping by a factor of 10 - we might get a similar speedup of Slicer build, too.

**Comment by Sunderlandkyl** [comment] 2022-03-02 21:40
There were a number of unnecessary linked ITK libraries in IGSIO that I've now removed. Hopefully that will reduce the command length.

**Comment by jcfr** [comment] 2022-03-02 22:14
> There were a number of unnecessary linked ITK libraries in IGSIO

After trying the updated repo, there were still issues. I just updated the dashboard script to use a short directory basename, this should help :crossed_fingers: 

> It is obscene that VTK adds about 380 include paths and ITK adds about 180, while they could add just 1 instead.

This is because `(ITK|VTK)_DIR` is associated with the build directory.

Now we updated the VTK version, it should be possible to start using VTK install tree while still supporting externally build of VTK modules like `vtkRenderingVR`, `vtkRenderingOpenVR`, ... 

That said, it would not be possible with ITK yet ... because externally building ITK module like [ITKVideoBridgeOpenCV](https://github.com/Slicer/SlicerOpenCV/blob/master/SuperBuild/External_ITKVideoBridgeOpenCV.cmake) requires an ITK build tree ...

**Comment by lassoan** [comment] 2022-03-10 03:12
I've reviewed all the failing extensions with the latest nightly on all operating systems and categorized them as:
- 5=must fix before releasing Slicer5
- 4, 3, 2 = would be nice to fix
- 1 = should be removed from the extensions index

The result is here:
https://docs.google.com/spreadsheets/d/1GC4DWDpOXhuDYdfYOjJ6PmjHTeMM3-K7SoiC5ZR1GYg/edit?usp=sharing

@jcfr @pieper @cpinter to get started, **could you please confirm if you were OK with removal of the following extensions from the extensions index**? These extensions were not available after Slicer-4.10.

DTI-Reg
MarginCalculator
exStone
SlicerWMA
DTIProcess
ABC
DTIAtlasFiberAnalyzer
IASEM
DTIAtlasBuilder
SlicerPathology
VirtualFractureReconstruction
DiceComputation
Cardiac_MRI_Toolkit
LightWeightRobotIGT
CBC_3D_I2MConversion
FiberViewerLight
DTIPrep
MABMIS
RSSExtension
FacetedVisualizer
AutoTract
SurfaceFragmentRegistration
MultiLevelRegistration
SupervisedSegmentationToolbox
Eigen3

**Comment by pieper** [comment] 2022-03-10 22:21
it would be great if SlicerWMA could be saved.

**Comment by pieper** [comment] 2022-03-10 22:22
Based on [this post](https://discourse.slicer.org/t/slicerdmri-cannot-be-installed/22441/2) we should add SlicerDMRI to the list.

**Comment by lassoan** [comment] 2022-03-10 23:31
The list of extensions that we must/should/may fix is in the [linked spreadsheet](https://docs.google.com/spreadsheets/d/1GC4DWDpOXhuDYdfYOjJ6PmjHTeMM3-K7SoiC5ZR1GYg/edit?usp=sharing) and it already lists SlicerDMRI as a "must fix".

I'll update the checklist at the top once we agreed which extensions we require to fix before Slicer5.

**Comment by jamesobutler** [comment] 2022-03-14 23:44
@pieper Is SlicerWMA actually being used? I noticed that @jcfr issued PR https://github.com/SlicerDMRI/SlicerWMA/pull/4 to fix a build error back in April 2019 and it never was merged. It corresponds to https://slicer.cdash.org/viewBuildError.php?buildid=2585718 which is as recent as Feb 9th 2022.

**Comment by MichaelColonel** [comment] 2022-03-15 07:21
SlicerRT has been updated and successfully compiled under Linux and Mac.

**Comment by pieper** [comment] 2022-03-15 19:27
> @pieper Is SlicerWMA actually being used?

I'm not sure if it is being used but it would be helpful.  The whitematteranalysis pip package doesn't install in Slicer python (needs to build wheels and fails without Python.h) so having the extension available is better.

**Comment by Sunderlandkyl** [comment] 2022-03-21 14:35
SlicerIGSIO is building successfully again on the dashboard. Fixed in this commit: https://github.com/IGSIO/IGSIO/commit/e614b64af008df7cae4e22d3135c82567809ccb9.

**Comment by lassoan** [comment] 2022-03-23 18:44
@RafaelPalomar could you help with fixing SlicerCIP extension build errors on Linux?

https://slicer.cdash.org/viewBuildError.php?buildid=2637203

Note that SlicerCIP and ChestImagingPlatform are now forked into the Slicer organization, so if you can fix things then please submit pull request at https://github.com/Slicer/SlicerCIP and https://github.com/Slicer/ChestImagingPlatform.

Thank you!

**Comment by lassoan** [comment] 2022-03-23 18:47
@cpinter could you look into fixing the SlicerVirtualReality extension build?

https://slicer.cdash.org/build/2638183/configure

It seems that the issue is that git protocol is attempted to be used for anonymous access, which is not an option anymore. In other repositories we hardcoded to use https for cloning from repositories on github. Thank you!

**Comment by RafaelPalomar** [comment] 2022-03-24 13:44
> @RafaelPalomar could you help with fixing SlicerCIP extension build errors on Linux?

@lassoan, I have opened Slicer/ChestImagingPlatform#2 which should fix the build errors.

**Comment by lassoan** [comment] 2022-03-25 18:07
computron-macos-tests.kitware fails to build many extensions, probably due to some configuration error. @sjh26 Could you disable extension builds on this computer so that it does not pollute the dashboard?

**Comment by jcfr** [comment] 2022-03-25 18:37
Will take care of this before the end of the day, now taking a break.

**Comment by jcfr** [comment] 2022-03-25 22:58
Looks like all failure associated with `computron` are legitimate:
https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=site&compare1=63&value1=computron

For example, the build of `SPHARM-PDM` is failing consistently, see https://slicer.cdash.org/index.php?project=SlicerPreview&date=2022-03-25&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SPHARM-PDM

and `ModelToModelDistance` is also successful on all of the dashboard, see https://slicer.cdash.org/index.php?project=SlicerPreview&date=2022-03-25&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ModelToModel

**Comment by jamesobutler** [comment] 2022-03-25 23:12
I assume factory-south-macos will be retired from SlicerPreview duty soon and replaced by computron with the deployment minimum target updated to macOS 10.14 in https://github.com/Slicer/Slicer/pull/6108. I believe hardware was preventing factory-south-macos from being upgraded beyond macOS 10.13.

**Comment by lassoan** [comment] 2022-03-26 00:53
There are 5 extensions that only fail to build on computron but builds without problems on the other macOS factory machine:
- SlicerWMA: https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SlicerWMA
- SlicerJupyter: https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SlicerJupyter
- SlicerITKUltrasound: https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SlicerITKUltrasound
- SkeletalRepresentation: https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SkeletalRepresentation
- MeshToLabelmap: https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=MeshToLabelmap

**Comment by jamesobutler** [comment] 2022-03-27 16:07
Modules that fail to instantiate provide false hope to users that they can actually use the extension and often leads to post on the discourse forum about why it isn't working. I propose actions to remove or fix the following extensions which have startup errors as seen in the python console:
- [ ] [ShapeQuantifier](https://github.com/jbvimort/ShapeQuantifierExtension) fails [py_ShapeQuantifier](https://slicer.cdash.org/test/21885977) and includes other extension's modules? (AnglePlanes, EasyClip, MeshStatistics, PickAndPaint, Q3DC, ShapeQuantifier). It is including old versions of these modules before they were updated to Python 3.
- [ ] [DatabaseInteractor](https://github.com/DCBIA-OrthoLab/DatabaseInteractorExtension) fails [py_DatabaseInteractor](https://slicer.cdash.org/test/21884278)
    - Not updated to Python 3
- [ ] [CornerAnnotation](https://github.com/ayamada0614/CornerAnnotation) fails [py_CornerAnnotation](https://slicer.cdash.org/test/21884144)
    - Not updated to Python 3
- [ ] [PercutaneousApproachAnalysis](https://github.com/SNRLab/PercutaneousApproachAnalysis) fails [py_PercutaneousApproach](https://slicer.cdash.org/test/21885579)
    - Not updated to Python 3
- [ ] [DeepInfer](https://github.com/DeepInfer/Slicer-DeepInfer) fails [py_DeepInfer](https://slicer.cdash.org/test/21884280)
    - Not updated to Python 3
- [ ] [XNATSlicer](https://github.com/NrgXnat/XNATSlicer) fails [py_XNATSlicer](https://slicer.cdash.org/test/21886416)
    - Not updated to Python 3
- [ ] [OpenCAD](https://github.com/vnarayan13/Slicer-OpenCAD) Python 3 issues? https://slicer.cdash.org/test/21884631
    - Not updated to Python 3
- [ ] [lapdBrowser](https://github.com/lapdMouse/Slicer-lapdMouseBrowser) fails [py_lapdMouseDBBrowser](https://slicer.cdash.org/test/21886425)
    - lapdMouseDBBrowser module fails to instantiate
    - lapdMouseVisualizer instantiates successfully
- [ ] [DiffusionQC](https://github.com/pnlbwh/SlicerDiffusionQC) fails [py_GradQC](https://slicer.cdash.org/test/21884505)
    - Appears to have had issued with GradQC for awhile re https://github.com/pnlbwh/SlicerDiffusionQC/issues/46

**Comment by pieper** [comment] 2022-03-27 16:51
Yes, I agree.  Not to give up on these, but extensions that don't work are a bad reflection on the core application.  I hope the original contributors or future maintainers can pick these up at some point.  They are probably not too hard to fix.

**Comment by revmic** [comment] 2022-04-21 01:50
We recently made some changes to the [XNATSlicer](https://github.com/NrgXnat/XNATSlicer) module and pulled in some python 2to3 changes made by Andras. It's been tested on the latest 4.11 and 4.13 Slicer releases. Any advice on what I can do to get this extension added back to the index? Thanks!

**Comment by pieper** [comment] 2022-04-21 15:54
That's great to hear @revmic - you can just make a PR to the https://github.com/Slicer/ExtensionsIndex to move the file out of archive and into the toplevel directory.

**Comment by revmic** [comment] 2022-04-21 19:24
PR created. Thanks for the quick response!

**Comment by jcfr** [comment] 2022-04-30 00:05
Closing. Extensions have been either archived or fixed.

The last outstanding one is https://github.com/SlicerDMRI/SlicerWMA that is failing to build on `computron`

![image](https://user-images.githubusercontent.com/219043/166082254-b6e2f0b7-f5b4-4c5d-bfdd-672fd288b43a.png)

**Closed by jcfr** 2022-04-30 00:05 UTC
Labels: type:bug
