### ISSUE TITLE
Volume rendering file shows up as changed in Save dialog directly after opening an mrml scene

### ISSUE THREAD

**Issue by oqilipo** [Slicer/Slicer#8030] opened 2024-11-04 20:52 UTC
## Summary
The *.vp volume rendering file shows up as changed in Save dialog directly after opening an MRML scene.
Probably a bug in the code that manages the ModifiedSinceRead property of the node.

![cbf736ffb6e2cdca65731761a81d4db942aece43](https://github.com/user-attachments/assets/ffc63ecf-e01c-4d93-a611-cb9076679aab)

## Steps to reproduce

Download the example scene: [Upload Files | Free File Upload and Transfer Up To 10 GB](https://easyupload.io/9mbf6h)

1. Open the scene
2. Open the Save Dialog

## Environment
- Slicer version: Slicer 5.6.2 r32448 / f10cd8c
- Operating system: Windows 11

**Comment by lassoan** [comment] 2024-11-04 23:06
The issue is fixed in this pull request:

https://github.com/Slicer/Slicer/pull/8029

**Closed** 2024-11-12 03:55 UTC
Labels: Type: Bug
