### ISSUE TITLE
Right-click context menu usability issues

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5734] opened 2021-07-10 13:56 UTC
- [x] If you right-click on a markup point and turn on the "Interaction" visibility action with visible handles, then right-click on the markup cannot bring up the markup context menu anymore. It will only bring up the slice view context menu. Therefore you have to manually navigate to the markups module to turn off the "Interaction" visibility to be able to use the markup right-click context menu again.
  - Remaining task: display translate/rotate/scale handles over control points (https://github.com/Slicer/Slicer/pull/5756#issuecomment-887771981)
- [x] When I'm using the "Draw" Segment Editor effect and use "Right-click" to apply the segment, the slice view context menu is appearing and then I have to click away from it and then the segment is applied. Maybe this effect needs an actual apply button? Or different method to end the interaction to apply? Or the context menu logic should know if the draw effect is active to not bring up context menu stuff?
- [ ] If you are using the Surface Cut or Draw Tube segment editor effect from SegmentEditorExtraEffects extension, you can right-click on a markup point and select "Delete markup" which will delete the `segmentMarkupNode` object used by the effect and mess up its usage. Maybe there should be customizations done to hide some markups context menu actions while using Segment Editor effects? I'm not sure if there are other uses of markups in other modules where the default "Delete Markup" action could mess up some internal logic where a markup node is being used.
  - Remaining task: hide "Delete markup node" menu action

## Environment
- Slicer version: Slicer-4.13.0-2021-07-09
- Operating system: Windows

**Comment by lassoan** [comment] 2021-07-10 14:11
> If you right-click on a markup point and turn on the "Interaction" visibility action with visible handles, then right-click on the markup cannot bring up the markup context menu anymore

I could not reproduce this. Could you debug into this? Does the code get to qSlicerSubjectHierarchyMarkupsPlugin::showViewContextMenuActionsForItem?

> When I'm using the "Draw" Segment Editor effect and use "Right-click" to apply the segment

Could you try if you can use double-click event would work well for finishing the placement? You can also hit the `Enter` key and of course it would not hurt to have an "Apply" button either.

> If you are using the Surface Cut or Draw Tube segment editor effect from SegmentEditorExtraEffects extension, you can right-click on a markup point and select "Delete markup"

We could add a custom Subject Hierarchy plugin that would only offer selected actions, but probably it would be simpler for developers if we allowed to control which options are visible for a particular markup node by custom node attributes. For example, `Markups.ViewContextMenu.EnableDeleteNode`, `Markups.ViewContextMenu.EnableRenamePoint`,... node attributes could be checked in `qSlicerSubjectHierarchyMarkupsPlugin::showViewContextMenuActionsForItem` to decide which action should be made visible.

**Comment by jamesobutler** [comment] 2021-07-10 18:46
Not being able to access the markups context menu while the interactive handles are visible, here is a video:

https://user-images.githubusercontent.com/15837524/125173031-dcbc5a80-e18a-11eb-9c13-42885dd9824c.mp4

In regards to the "Draw" segment editor effect, double right-click would be a little weird as generally double right-click in other applications is not ever mapped to an action.  Having an apply button would be more clear like some other segment effects. Maybe the "a" key just becomes the only shortcut to apply with the removal of the right-click (would need to update documentation). I can already imagine people asking on the discourse forum getting confused with single right-click and double right-click. I think when using left-click-and-drag for continuous placement, I would actually find it nice if it applied automatically upon releasing (similar to how scissors performs or how left-click-and-drag of the Paint effect works). However this wouldn't work with the single click point placement functionality for Draw.

**Comment by lassoan** [comment] 2021-07-10 20:03
Double-left-click is the usual gesture to close a contour, it just was not available in earlier VTK versions. We can use it now.

We'll indeed need to merge Draw and Scissors effect in the future, with both manual and automatic apply mode.

**Comment by jamesobutler** [comment] 2021-07-10 20:15
Yes double left click could work as it is usually like an enter event. That would be good as a quick improvement rather than single right click to apply and also adding of the apply button would be good to have so that it isn’t only possible with mouse button/keyboard interaction.

**Comment by lassoan** [comment] 2021-07-26 14:05
All the issues have now been fixed. @jamesobutler please test it in the Slicer Preview Release tomorrow.

**Comment by jamesobutler** [comment] 2021-07-26 17:47
Is there a reason you have maintained right-click to complete the Draw effect? It really only works well if you have customized the right-click context menu to not have any of the following actions whitelisted in `allowedViewContextMenuActionNames`. 
![image](https://user-images.githubusercontent.com/15837524/127034521-c4923b98-cb84-423a-ae0f-9993d052471b.png)

Should right-click to apply for Draw only be allowed if it doesn't bring up a context menu? So either it applies the segment or brings up the context menu, but never both as that is the "BUG" here.

**Comment by lassoan** [comment] 2021-07-26 18:01
I kept the right click mainly to avoid unnecessary annoying the users with requiring changing how they work. There is also a slight difference in how the contour is finished (on double-click a point is added to the current position before closing the contour).

Right-click does not bring up context menu anymore when using the Drawing effect.

**Comment by jamesobutler** [comment] 2021-07-26 18:14
Which commit resolved the following point?

> If you right-click on a markup point and turn on the "Interaction" visibility action with visible handles, then right-click on the markup cannot bring up the markup context menu anymore. It will only bring up the slice view context menu. Therefore you have to manually navigate to the markups module to turn off the "Interaction" visibility to be able to use the markup right-click context menu again.

https://github.com/Slicer/Slicer/issues/5734#issuecomment-877685296

**Comment by lassoan** [comment] 2021-07-26 18:53
> If you are using the Surface Cut or Draw Tube segment editor effect from SegmentEditorExtraEffects extension, you can right-click on a markup point and select "Delete markup"

For reference, this is fixed in https://github.com/Slicer/Slicer/commit/f9f11666e8ce695daca920b6ef265b7720089f34

> Which commit resolved the following point? Referring to the interaction "Translate" handles.

I thought this has been fixed (I've tested it on ROI nodes, and clicking on the ROI box lines worked fine; tested on fiducials and it worked fine because the handles did not cover the fiducial points), but I've tested it more now and indeed if you only have a single fiducial then there is nothing left to right-click on other than the interaction handles. I've submitted a PR that enables context menu when right-clicking on interaction handles - https://github.com/Slicer/Slicer/pull/5756

**Comment by jamesobutler** [comment] 2021-07-26 19:44
> > If you are using the Surface Cut or Draw Tube segment editor effect from SegmentEditorExtraEffects extension, you can right-click on a markup point and select "Delete markup"
> 
> For reference, this is fixed in https://github.com/Slicer/Slicer/commit/f9f11666e8ce695daca920b6ef265b7720089f34

That appears to fix the ability of pressing the "Edit Properties" action, but not the "Delete markup" action which can delete the internally used `segmentMarkupNode` of SurfaceCut or DrawTube. `segmentMarkupNode` is also a hidden node. I would think if a node is hidden, then it should not support being deleted with the right-click context menu. https://github.com/lassoan/SlicerSegmentEditorExtraEffects/blob/86ccd9f223c0eddef913f7977ceeac67e84934ce/SegmentEditorSurfaceCut/SegmentEditorSurfaceCutLib/SegmentEditorEffect.py#L341
![image](https://user-images.githubusercontent.com/15837524/127049113-4978e082-4f5f-4eba-9e49-089b1c907108.png)

**Comment by lassoan** [comment] 2021-07-26 20:29
We had a strong reason to hide the "Edit properties..." action, but hardcoding hiding "Delete markup..." for hidden nodes would be quite arbitrary. It is handy if I can remove all the points at once. Would you also hide "Edit markup terminology..."? For these segment editor effects, renaming points and toggle selection does not make sense either - should we hide those, too?

I see a few different solutions:
- Option A: make sure in the Segment Editor effect that "Delete markup" action is handled correctly
- Option B: specify a scripted subject hierarchy plugin that takes ownership of this markup and make it not show any actions or show only the delete point action. (see example [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#subject-hierarchy-plugin-offering-view-context-menu-action))
- Option C: allow specifying the allowed action list via a node attribute (`SubjectHierarchy.allowedViewContextMenuActionNames`) similarly as shown [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#use-whitelist-to-customize-view-menu), but not specified globally but only for a node

**Comment by jamesobutler** [comment] 2021-07-26 20:38
I would think only the Interaction related actions would be supported if the clicked node was marked hidden from editors. If it is marked as "Hidden", I think that is generally done as way to prevent it from being edited.

**Comment by lassoan** [comment] 2021-07-27 19:33
@cpinter @Sunderlandkyl what do you think about option C above - specifying a MRML node attribute (or maybe a proper node member) that would specify a list of allowed ViewContextMenu actions? We have infrastructure for disabling context menu actions globally, but not for each node. We could address this by creating a custom SH plugin but it would be a bit of an overhead and for each case but there we would need to reimplement all actions that we do want to appear.

**Closed** 2021-09-10 00:30 UTC
Labels: type:bug
