### ISSUE TITLE
Markup ROI interaction inverted

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#6459] opened 2022-07-08 08:21 UTC
## Summary

In certain scenarios, the behavior of the ROI interaction control is unexpected, and it depends on the actual camera position. See video:

https://user-images.githubusercontent.com/1325980/177949276-5d0775ab-3b12-4683-8fb5-279ad81a97ad.mp4

## Steps to reproduce

* Load scene (less than 10MB): https://1drv.ms/u/s!Ao_a-dPPX98ZhdwviFcE6ARoz5O5kA?e=DNuxBS
* Move the orange interaction handle to move the ROI in the 3D view
* Rotating the 3D view will change the relationship between the mouse movement and the resulting transform

## Expected behavior

* ROI moves together with the mouse

## Environment
- Slicer version: Slicer-5.0.2 + locally built 5.1-2022-007-01
- Operating system: Windows 10

**Comment by Sunderlandkyl** [comment] 2022-07-08 18:14
Should be fixed in [661e009](https://github.com/Slicer/Slicer/commit/661e00945f7a1f695e939366bcaf10e9481f2ada).

**Comment by lassoan** [comment] 2022-10-17 20:57
The issue is fixed (comment/reopen if there are still problems).

**Closed by lassoan** 2022-10-17 20:57 UTC
Labels: type:bug

**Comment by cpinter** [comment] 2022-10-18 11:01
Absolutely, thank you! Also for the fix @Sunderlandkyl ! Back in the day didn't notice the update.
