### ISSUE TITLE
Python executable as a virtual environment - add to DOCs

### ISSUE THREAD

**Issue by koegl** [Slicer/Slicer#6465] opened 2022-07-13 19:30 UTC
## Is your feature request related to a problem? Please describe.

I just found out in a [Discourse post](https://discourse.slicer.org/t/basic-pycharm-importation-analysis-for-slicer-development/8509) that in PyCharm (but probably also in other IDEs) you can use the Slicer Python executable as a virtual environment, which is really helpful, especially for beginners, as then you have code completion etc in your IDE.

## Describe the solution you'd like
I would like to add this to the Slicer documentation, but I'm not sure where.

I guess it could be added to the debugging documentation on [readthedocs](https://slicer.readthedocs.io/en/latest/developer_guide/debugging/overview.html#python-debugging) or to the [SlicerDebuggingTools](https://github.com/SlicerRt/SlicerDebuggingTools) repo, but I'm not sure if that's the right place, because only people trying to use a debugger would stumble upon this very helpful feature.

**Comment by jcfr** [comment] 2022-07-21 20:55
This could be added to the Python FAQ. See https://slicer.readthedocs.io/en/latest/developer_guide/python_faq.html#

That said, I am not sure on what would be the best FAQ entry title.

A possible candidate: _How to specify PythonSlicer as interpreter in Python IDEs?_

**Comment by lassoan** [comment] 2022-07-22 05:49
@koegl What exactly were you able to get with setting PythonSlicer.exe as interpreter? Do documentation and autocomplete work for all classes and all methods in them? In the past only a small fraction of classes and methods were found.

**Comment by koegl** [comment] 2022-08-04 22:10
I was trying to get autocomplete, but you're right, it doesn't work for all classes - however, it's still quite helpful

**Comment by jcfr** [comment] 2023-07-11 14:40
Closing. This is a duplicate of:
* https://github.com/Slicer/Slicer/issues/6690

**Closed by jcfr** 2023-07-11 14:40 UTC
Labels: type:enhancement, type:documentation
