### ISSUE TITLE
Slicer crashes while on BoneReconstructionPlanner workflow

### ISSUE THREAD

**Issue by mauigna06** [Slicer/Slicer#6570] opened 2022-10-09 13:10 UTC
## Summary

Hi. I got to make the [crash](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/issues/63) to happen while debugging on RelWithDebInfo

Here is a screenshot:
<img width="1280" alt="BRP_Slicer_bug" src="https://user-images.githubusercontent.com/19158307/194758388-a3abe633-c4b4-4049-bd73-d290dff02056.png">

## Steps to reproduce

It's hard to reproduce, there are two buttons that sometimes cause it. I have the debugging session open. Can I share it somehow?

## Expected behavior

Slicer doesn't crash

## Environment
- Slicer version: Slicer-5.1.0-2022-10-07
- Operating system: Windows 11

**Comment by pieper** [comment] 2022-10-09 14:14
@mauigna06 to help debug this please write a script (SelfTest) that can be used to reproduce the issue on other machines.

**Comment by mauigna06** [comment] 2022-10-09 18:33
Hi @pieper. Thanks for the answer.

Below is a script that reproduces the crash using the python interactor (you only need to add BoneReconstructionPlanner to your module paths):
```

def createSkinModel():
    import SampleData
    sampleDataLogic = SampleData.SampleDataLogic()
    masterVolumeNode = sampleDataLogic.downloadMRHead()
    #
    # Create segmentation
    segmentationNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLSegmentationNode")
    segmentationNode.CreateDefaultDisplayNodes() # only needed for display
    segmentationNode.SetReferenceImageGeometryParameterFromVolumeNode(masterVolumeNode)
    addedSegmentID = segmentationNode.GetSegmentation().AddEmptySegment("skin")
    #
    # Create segment editor to get access to effects
    segmentEditorWidget = slicer.qMRMLSegmentEditorWidget()
    segmentEditorWidget.setMRMLScene(slicer.mrmlScene)
    segmentEditorNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLSegmentEditorNode")
    segmentEditorWidget.setMRMLSegmentEditorNode(segmentEditorNode)
    segmentEditorWidget.setSegmentationNode(segmentationNode)
    segmentEditorWidget.setMasterVolumeNode(masterVolumeNode)
    #
    # Thresholding
    segmentEditorWidget.setActiveEffectByName("Threshold")
    effect = segmentEditorWidget.activeEffect()
    effect.setParameter("MinimumThreshold","35")
    effect.setParameter("MaximumThreshold","695")
    effect.self().onApply()
    #
    # Clean up
    segmentEditorWidget = None
    slicer.mrmlScene.RemoveNode(segmentEditorNode)
    #
    # Make segmentation results visible in 3D
    segmentationNode.CreateClosedSurfaceRepresentation()
    #
    skinModelNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLModelNode")
    skinModelNode.SetName("skin")
    skinModelNode.CreateDefaultDisplayNodes()
    segmentID = segmentationNode.GetSegmentation().GetNthSegmentID(0)
    segment = segmentationNode.GetSegmentation().GetSegment(segmentID)
    logic = slicer.modules.segmentations.logic()
    logic.ExportSegmentToRepresentationNode(segment, skinModelNode)



# Test starts here
createSkinModel()

slicer.util.selectModule('BoneReconstructionPlanner')
slicer.app.processEvents()

slicer.modules.BoneReconstructionPlannerWidget.ui.createFibulaCylindersFiducialListButton.click()


# Select skin model where it says "Select fibula surgical guide base"
# Delete skin model using the context menu of the data module
# Export visible segments to models (so the skin model is created again)
# Enter the BoneReconstructionPlanner module
# Click on "Create cylinder from fiducial list and fibula surgical guide base" <-- Slicer crashes here

```

I tested with yesterday's build an it does crash there

**Comment by lassoan** [comment] 2022-10-10 01:38
@mauigna06 this is awesome, based on these information we'll be able to fix this issue easily.

Could you reproduce the issue again with your RelWithDebInfo build? If you can, then please inspect the stack trace when it occurs: take a screenshot of the last couple of stack frames and "Auto" variables window. That will shows exactly where and why the crash occurred. 

If you don't have time to do it then I'll try to find some time for it in the next few days.

**Comment by mauigna06** [comment] 2022-10-10 11:01
Hi @lassoan.

Here is the callstack:

```
>	Qt5Core.dll!QSortFilterProxyModel::parent(const QModelIndex & child) Line 2176	C++
 	[Inline Frame] Qt5Core.dll!QModelIndex::parent() Line 443	C++
 	Qt5Core.dll!QAbstractItemModelPrivate::rowsAboutToBeRemoved(const QModelIndex & parent, int first, int last) Line 823	C++
 	Qt5Core.dll!QAbstractItemModel::beginRemoveRows(const QModelIndex & parent, int first, int last) Line 2820	C++
 	[Inline Frame] Qt5Core.dll!QSortFilterProxyModelPrivate::remove_proxy_interval(QVector<int> &) Line 784	C++
 	Qt5Core.dll!QSortFilterProxyModelPrivate::remove_source_items(QVector<int> & source_to_proxy, QVector<int> & proxy_to_source, const QVector<int> & source_items, const QModelIndex & source_parent, Qt::Orientation orient, bool emit_signal) Line 765	C++
 	Qt5Core.dll!QSortFilterProxyModelPrivate::source_items_about_to_be_removed(const QModelIndex & source_parent, int start, int end, Qt::Orientation orient) Line 1066	C++
 	[Inline Frame] Qt5Core.dll!QSortFilterProxyModelPrivate::_q_sourceRowsAboutToBeRemoved(const QModelIndex &) Line 1689	C++
 	Qt5Core.dll!QSortFilterProxyModel::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 283	C++
 	Qt5Core.dll!doActivate<0>(QObject * sender, int signal_index, void * * argv) Line 3903	C++
 	[Inline Frame] Qt5Core.dll!QAbstractItemModel::rowsAboutToBeRemoved(const QModelIndex & _t2, int _t3, int _t4, QAbstractItemModel::QPrivateSignal) Line 599	C++
 	Qt5Core.dll!QAbstractItemModel::beginRemoveRows(const QModelIndex & parent, int first, int last) Line 2819	C++
 	Qt5Gui.dll!QStandardItemModelPrivate::rowsAboutToBeRemoved(QStandardItem * parent, int start, int end) Line 643	C++
 	Qt5Gui.dll!QStandardItem::removeRows(int row, int count) Line 1800	C++
 	Qt5Gui.dll!QStandardItemModel::removeRows(int row, int count, const QModelIndex & parent) Line 2995	C++
 	qSlicerSubjectHierarchyModuleWidgets.dll!qMRMLSubjectHierarchyModel::onSubjectHierarchyItemAboutToBeRemoved(__int64 itemID) Line 1498	C++
 	vtkCommon-9.1.dll!vtkCallbackCommand::Execute(vtkObject * caller, unsigned long event, void * callData) Line 42	C++
 	vtkCommon-9.1.dll!vtkSubjectHelper::InvokeEvent(unsigned long event, void * callData, vtkObject * self) Line 651	C++
 	MRMLCore.dll!vtkMRMLNode::InvokeCustomModifiedEvent(int eventId, void * callData) Line 583	C++
 	MRMLCore.dll!vtkMRMLSubjectHierarchyNode::ItemEventCallback(vtkObject * caller, unsigned long eid, void * clientData, void * callData) Line 3662	C++
 	vtkCommon-9.1.dll!vtkCallbackCommand::Execute(vtkObject * caller, unsigned long event, void * callData) Line 42	C++
 	vtkCommon-9.1.dll!vtkSubjectHelper::InvokeEvent(unsigned long event, void * callData, vtkObject * self) Line 651	C++
 	MRMLCore.dll!vtkSubjectHierarchyItem::RemoveChild(vtkSubjectHierarchyItem * item) Line 1129	C++
 	MRMLCore.dll!vtkMRMLSubjectHierarchyNode::RemoveItem(__int64 itemID, bool removeDataNode, bool recursive) Line 2720	C++
 	[Inline Frame] MRMLCorePython.pyd!vtkPythonArgs::ErrorOccurred() Line 843	C++
 	MRMLCorePython.pyd!PyvtkMRMLSubjectHierarchyNode_RemoveItem(_object * self, _object * args) Line 1153	C++
 	[External Code]	
 	PythonQt.dll!PythonQtSignalTarget::call(_object * callable, const PythonQtMethodInfo * methodInfos, void * * arguments, bool skipFirstArgumentOfMethodInfo) Line 130	C++
 	PythonQt.dll!PythonQtSignalTarget::call(void * * arguments) Line 57	C++
 	PythonQt.dll!PythonQtSignalReceiver::qt_metacall(QMetaObject::Call c, int id, void * * arguments) Line 275	C++
 	Qt5Core.dll!doActivate<0>(QObject * sender, int signal_index, void * * argv) Line 3918	C++
 	[Inline Frame] Qt5Widgets.dll!QAbstractButton::clicked(bool _t1) Line 308	C++
 	Qt5Widgets.dll!QAbstractButtonPrivate::emitClicked() Line 417	C++
 	Qt5Widgets.dll!QAbstractButtonPrivate::click() Line 409	C++
 	Qt5Widgets.dll!QAbstractButton::mouseReleaseEvent(QMouseEvent * e) Line 1045	C++
 	Qt5Widgets.dll!QWidget::event(QEvent * event) Line 9082	C++
 	Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3634	C++
 	Qt5Widgets.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3076	C++
 	qSlicerBaseQTGUI.dll!qSlicerApplication::notify(QObject * receiver, QEvent * event) Line 428	C++
 	Qt5Core.dll!QCoreApplication::notifyInternal2(QObject * receiver, QEvent * event) Line 1063	C++
 	Qt5Widgets.dll!QApplicationPrivate::sendMouseEvent(QWidget * receiver, QMouseEvent * event, QWidget * alienWidget, QWidget * nativeWidget, QWidget * * buttonDown, QPointer<QWidget> & lastMouseReceiver, bool spontaneous, bool onlyDispatchEnterLeave) Line 2614	C++
 	Qt5Widgets.dll!QWidgetWindow::handleMouseEvent(QMouseEvent * event) Line 685	C++
 	Qt5Widgets.dll!QWidgetWindow::event(QEvent * event) Line 301	C++
 	Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3634	C++
 	Qt5Widgets.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3586	C++
 	qSlicerBaseQTGUI.dll!qSlicerApplication::notify(QObject * receiver, QEvent * event) Line 428	C++
 	Qt5Core.dll!QCoreApplication::notifyInternal2(QObject * receiver, QEvent * event) Line 1063	C++
 	Qt5Gui.dll!QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent * e) Line 2283	C++
 	Qt5Gui.dll!QWindowSystemInterface::sendWindowSystemEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 1175	C++
 	Qt5Core.dll!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 530	C++
 	qwindows.dll!QWindowsGuiEventDispatcher::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 74	C++
 	[Inline Frame] Qt5Core.dll!QEventLoop::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag>) Line 139	C++
 	Qt5Core.dll!QEventLoop::exec(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 232	C++
 	Qt5Core.dll!QCoreApplication::exec() Line 1371	C++
 	qSlicerBaseQTCore.dll!qSlicerCoreApplication::exec() Line 967	C++
 	SlicerApp-real.exe!`anonymous namespace'::SlicerAppMain(int argc, char * * argv) Line 62	C++
 	[External Code]	

```

And below is a screenshot (I don't know why but autos window is empty):

<img width="1280" alt="stackTraceSlicerBug" src="https://user-images.githubusercontent.com/19158307/194851479-0a53d451-cbda-40c4-9350-47491af04596.png">

Please let me know if I have to do anything else to help solving this

**Comment by lassoan** [comment] 2022-10-10 12:25
These scene model update issues can be very complex. There are some known issues but they don't cause crash.

@Sunderlandkyl would you have time to investigate this? The 5.2 release is planned within days and it would be great if a fix for this could be included.

**Comment by Sunderlandkyl** [comment] 2022-10-11 00:43
Sure, I'll take a look at it.

**Comment by mauigna06** [comment] 2022-10-11 13:45
Thank you very much Kyle

**Comment by Sunderlandkyl** [comment] 2022-10-11 16:58
I haven't been able to reproduce the crash so far on a RelWithDebInfo build.

Steps that I followed:
- Paste above code into interactor
- Select skin model in BoneReconstructionPlanner where it says "Select fibula surgical guide base"
- Switch to data module
- Right-click and on skin model and "Delete"
- Right-click on segmentation and "Export visible segments to models"
- Switch back to "BoneReconstructionPlanner"
- Click "Create cylinders from fiducial list and fibula surgical guide base"

Do I need to place a fiducial point at some point to cause the crash?

**Comment by mauigna06** [comment] 2022-10-11 17:05
@Sunderlandkyl I just got it to crash again. I'm doing a video. Please give me some minutes while I upload it.

**Comment by mauigna06** [comment] 2022-10-11 17:35
Here you have @Sunderlandkyl 

https://user-images.githubusercontent.com/19158307/195160557-6b75e97b-f7d6-47e6-99f8-0e58cd58a57c.mp4

**Comment by Sunderlandkyl** [comment] 2022-10-11 18:36
The crash doesn't always happen for me, but if I repeatedly go back and forth between the BoneReconstructionPlanner and data module, deleting and recreating the skin each time, I can eventually reproduce it.

**Comment by mauigna06** [comment] 2022-10-11 18:43
> I can eventually reproduce it.

That's great

**Comment by lassoan** [comment] 2022-10-21 19:37
@Sunderlandkyl we are getting very close (within a few days?) to finish everything for Slicer-5.2. Do you think this fix could fit in?

**Comment by Sunderlandkyl** [comment] 2022-10-21 20:24
I think I have a fix. I'll make a PR shortly.

**Comment by Sunderlandkyl** [comment] 2022-10-21 20:34
Should be fixed by #6614.

**Comment by mauigna06** [comment] 2022-10-21 21:30
@Sunderlandkyl thank you so much!

**Comment by cpinter** [comment] 2022-10-24 14:23
@Sunderlandkyl Thank you very much for fixing the crash, it is really great! Can you please help me fully understand what happens and why the commit fixes the issue? Specifically this part: "This seems to cause an invalid SH item parent, and could cause a crash later when the model is updated." Do I understand correctly that the issue was that the folder node was in this case child of the segmentation (sibling of the virtual segment items)? Do you know why it became invalid?

**Comment by Sunderlandkyl** [comment] 2022-10-24 14:33
> Do I understand correctly that the issue was that the folder node was in this case child of the segmentation (sibling of the virtual segment items)? Do you know why it became invalid?

Yes, although I don't know why or at what point the parent Id becomes invalid.

**Comment by lassoan** [comment] 2022-10-24 14:49
I think

**Comment by cpinter** [comment] 2022-10-24 14:54
> adding some extra items there is unexpected and can cause unpredictable errors.

Yes, sounds reasonable. I was wondering if we had more info on this, fresh after Kyle's investigation, but it's OK, enough to know this much anyway. It is definitely unintended to place items among the virtual segment items. Thanks!

**Closed by cpinter** 2022-10-24 14:55 UTC
Labels: type:bug
