### ISSUE TITLE
Markups lines and curves are not visible in slice views after VTK9 upgrade

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5316] opened 2020-11-25 06:14 UTC
Markups lines and curves are not visible in slice views after VTK9 upgrade, only control points.

## Steps to reproduce

- Load MRHead
- Draw a line (or curve or angle) markups on a slice view
- Only control points appear, lines do not appear between them

![image](https://user-images.githubusercontent.com/307929/100190015-6ac52880-2ebb-11eb-8945-04cbd7325e75.png)

## Expected behavior

Full widget should appear, including lines.

## Environment
- Slicer version: Slicer master 2020-11-24, built with VTK9
- Operating system: Windows 10

**Comment by sankhesh** [comment] 2020-12-02 16:11
@lassoan Could you test with https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407

**Comment by jcfr** [comment] 2020-12-03 15:24
> @lassoan Could you test with https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407

The issue is reproducible with both [MR-7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407) and [MR-7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413) integrated. VTK was updated on Nov 20 Slicer master (see https://github.com/Slicer/Slicer/commit/31c89f230919a953e56f6722718281ce6da49e06).

**Comment by jcfr** [comment] 2020-12-04 02:41
Increasing glyph  size allows to see the line.

|  For example, setting glyph size at 7:60% | but then when using larger value (issue #5332) also appears
|----|-----|
| ![image](https://user-images.githubusercontent.com/219043/101114606-d429f300-35af-11eb-97b5-470f9dfd26b0.png)|![image](https://user-images.githubusercontent.com/219043/101114544-b0ff4380-35af-11eb-8b89-d5d2d74666b0.png)|
| ![image](https://user-images.githubusercontent.com/219043/101114744-16ebcb00-35b0-11eb-81e1-eb46adffde28.png)|![image](https://user-images.githubusercontent.com/219043/101114686-fe7bb080-35af-11eb-960b-db2bb13578a8.png)|

**Comment by jcfr** [comment] 2021-01-09 01:46
Closing. Issue fixed in https://github.com/Slicer/Slicer/commit/a96498c63dd986166b0dcd9e28cdeeed043285f5 after integrating #5361

**Closed by jcfr** 2021-01-09 01:46 UTC
Labels: domain:vtk9, type:bug
