### ISSUE TITLE
Extensions can not be installed

### ISSUE THREAD

**Issue by liamtimms** [Slicer/Slicer#5546] opened 2021-03-24 00:13 UTC
Hi all,

I've been using Slicer on Arch Linux without a problem via the `3dslicer-bin` package (which just downloads the binary from the slicer site and installs it on the system) for quite some time. You  can see the full `PKGBUILD` script (simply `bash` with some variables for use by the package manager) here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=3dslicer-bin
However, I'm hitting an issue with the extension manager in recent releases.

Previously, it seems Slicer happily installed extensions into `$XDG_CONFIG_HOME/NA-MIC/Extensions-<somenumbers>`. In the newest release, it seems like Slicer is attempting to write Extensions to `/opt/3dslicer/NA-MIC/Extensions-29738`. Since I'm usually running Slicer as a normal user but have it installed system-wide in `/opt/` this fails due to the lack of permission to change `/opt`. Ideally, I'd like to avoid running Slicer with full `sudo` powers and have it continue to use the old user-level directories for extensions.  Unfortunately, this also seems to be stopping me from effectively changing my user preferences. 

## Steps to reproduce

Install Slicer on Arch via the AUR PKGBUILD (see: https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#archlinux). Then launch the extension manager. 

## Expected behavior

I'd expect another folder to show up with the new Slicer release. My current NA-MIC user directory looks like this: 

```
~/.config/NA-MIC$ ls
Extensions-28257  Extensions-28701  Extensions-29402   Slicer-28257.ini  Slicer-28701.ini  Slicer-29402.ini  Slicer.ini
```

but Slicer is looking for `/opt/3dslicer/NA-MIC/Extensions-29738`  when I would expect it to create a new entry there. 

## Environment

Slicer:

```
Name            : 3dslicer-bin
Version         : 4.11.20210226-1
Description     : A multi-platform, free open source software package for visualization and medical image computing
Architecture    : x86_64
URL             : https://www.slicer.org
Provides        : 3dslicer
Depends On      : dbus  glib2
Required By     : None
Optional For    : python-nipype
Installed Size  : 1128.51 MiB
Packager        : Liam Timms <timms5000@gmail.com>
Build Date      : Mon 15 Mar 2021 12:02:09 PM EDT
Install Date    : Mon 15 Mar 2021 12:08:05 PM EDT
Install Reason  : Explicitly installed
```

Additional info on environment:

```
OS: Arch Linux x86_64
Kernel: 5.10.25-1-lts
DE: GNOME 3.38.4
```

**Comment by liamtimms** [comment] 2021-03-24 00:45
As a quick follow up, I realized after writing this that I could just modify the packaging to install Slicer into my `~/bin` and then `chown` the directory to belong to my user. Doing so works as expected and I see `Extensions-29738` and `Slicer-29738.ini` showing up in that directory now. I'm going to leave this issue open in case this change (and it's affect on system-level root installs) was not intended.

**Comment by lassoan** [comment] 2021-03-24 03:15
If you install Slicer as an administrator then you need to install all the extensions and Python packages, too. See some more explanation here: https://discourse.slicer.org/t/unable-to-install-extensions-when-slicer-is-installed-in-system-location/16588

**Comment by lassoan** [comment] 2021-03-24 03:23
Closing this, as the change was intended. I've added a note to the migration guide.

**Closed by lassoan** 2021-03-24 03:23 UTC
Labels: type:bug
