### ISSUE TITLE
Slices visible in 3D get color changes depending on view direction

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#8055] opened 2024-11-19 13:38 UTC
## Summary

See discussion [here:](https://discourse.slicer.org/t/slices-in-3d-views-are-blended-with-the-slice-view-colour-on-one-side/40260)

## Steps to reproduce

* Add sample data (i.e. MRHead)
* Make green view visible in 3D
* Switch to posterior view in 3D viewer

<img width="634" alt="image" src="https://github.com/user-attachments/assets/b1b3f9f0-02af-4b02-a08c-0006b7d52b06">

## Environment
- Slicer version: Slicer-5.7.0-2024-11-15
- Operating system: linux and mac

**Comment by pieper** [comment] 2024-11-19 13:39
Since Axial gets a red cast and coronal gets a green, I suspect there's something with backface material properties combined with texture in the displayable manager code.

**Comment by lassoan** [comment] 2024-11-19 15:28
I can reproduce it on Windows:

![image](https://github.com/user-attachments/assets/2c2f27b8-c24e-4e05-886b-2a17b7f5b2a9)

Of course this needs to be fixed, but it looks pretty cool. I'm wondering if this display mode could be useful somehow.

**Comment by Sunderlandkyl** [comment] 2024-11-19 15:45
There was some refactoring during https://github.com/Slicer/Slicer/commit/d6f6b7dbc2f797f8189b91b583d201dffd76d825 in vtkMRMLModelDisplayableManager::SetModelDisplayProperty to reduce code duplication, which probably cause the issue.

**Comment by lassoan** [comment] 2024-11-19 15:47
@Sunderlandkyl since you are the most familiar with the changes it would be great if you could investigate. Thank you!

**Comment by Sunderlandkyl** [comment] 2024-11-19 16:47
Should be fixed by #8056.

**Closed** 2024-11-19 18:30 UTC
