### ISSUE TITLE
Vanishing color table icons on volumes module

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#5834] opened 2021-09-02 13:51 UTC
When the user selects a scalar volume, switches to a labelmap and go back to the scalar volume, the icons of the lookup tables disappear:

![image](https://user-images.githubusercontent.com/4790289/131854761-9425f839-5fd6-409d-8861-7d2d552d8d69.png)

## Steps to reproduce

1. Load Mr. Head
2. Create a segmentation
3. Convert the segmentation to a labelmap
4. Go to volumes module
5. Select Mr. Head scalar volume
6. Select the labelmap
7. Selec Mr. Head again
8. Icons disappear

## Expected behavior

Keep the colormap icons

## Environment
- Slicer version: Slicer-4.13.0-2021-08-31
- Operating system: Windows 10

**Comment by lassoan** [comment] 2021-09-05 19:57
Thanks for reporting. The problem is fixed now.

**Closed** 2021-09-05 19:56 UTC
Labels: type:bug
