### ISSUE TITLE
"Display ROI" of volume rendering not synchonized

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#5730] opened 2021-07-08 10:35 UTC
"Display ROI" visible option of the crop tool in the volume rendering module is not synchronized with the selected volume

## Steps to reproduce

Load 2 volumes
In the volume rendering widget. On the first volume set "Display ROI"  visibility to true
Switch to the second volume
The "Display ROI"  visibility is true.

All other volume parameters (presets, etc.) are synchronized when switching the input node but not the "Display ROI"

## Expected behavior

I would expect that "Display ROI" should be synchronized when switching input volumes.

## Environment
- Slicer version: Slicer-4.13.00- personal build
- Operating system:  Linux 20.04

**Comment by lassoan** [comment] 2021-07-09 02:25
Thanks for reporting, the issue is now fixed.

**Closed** 2021-07-09 02:25 UTC
Labels: type:bug
