### ISSUE TITLE
dcmtk incorrectly decoding SEG files?

### ISSUE THREAD

**Issue by AGGDor** [Slicer/Slicer#5503] opened 2021-03-04 10:49 UTC
When I try and load SEG DICOM files created in a third-party program (Hermes Affinity Viewer) into Slicer, an error is thrown:
"E: Not enough bytes found in Pixel Data element. Found 342 bytes but 344 bytes expected."

I think this was raised as a side issue with dcmtk here: [https://github.com/QIICR/dcmqi/issues/341]

I am running:
- Slicer version: Slicer-4.13.0-2021-01-05
- Operating system: Windows 10 64-bit

Any advice/assistance would be greatly appreciated.

**Comment by lassoan** [comment] 2021-03-04 13:08
Thank you for reporting. As you can see, the right people know about this issue and working on it.

A potential fix is available, but needs to be tested. To help this move forward faster, you can build Slicer, apply the patch in DCMTK, and check if it indeed solves the problem with your file. Or, you can just wait until it gets fixed.

**Comment by AGGDor** [comment] 2021-03-04 13:12
Many thanks @lassoan 
As an absolute noob to Slicer, I'll give the experts a chance to do their thing before I charge blindly in...

**Comment by fedorov** [comment] 2021-03-04 13:57
@AGGDor when @hmeine suggested you open a new issue in https://github.com/QIICR/dcmqi/issues/341#issuecomment-790472653, he meant to open a new issue in the [dcmqi repository](https://github.com/QIICR/dcmqi/), not in Slicer.

I am closing this issue, since it is not specific to Slicer.

**Closed by fedorov** 2021-03-04 13:57 UTC
Labels: type:bug

**Comment by hmeine** [comment] 2021-03-05 10:43
Actually, *I* found Slicer to be not worse a location than dcmqi – after all, the origin of the problem is in dcmtk, so dcmqi did not appear to be a better fit than Slicer, and the problem was *noticed* in Slicer in this case. Therefore, Slicer users would maybe more easily find it here, and a discussion about a necessary dcmtk update with the patch in Slicer's superbuild would also fit better here.

Anyhow, I'm glad that it is resolved!

**Comment by fedorov** [comment] 2021-03-05 15:23
Hans, sorry for mis-representing your intent. I closed this issue before investigating the dcmqi issue completely, and realizing the patch has already been integrated into DCMTK. At the time, I thought the original issue is a purely dcmqi issue, and that is why I closed this issue.

Now that we know we need to update DCMTK and bring in the patch, it does deserve a Slicer issue, I believe.
