### ISSUE TITLE
Toggling empty markups folder visibility makes it disappear

### ISSUE THREAD

**Issue by malbi** [Slicer/Slicer#6596] opened 2022-10-18 15:46 UTC
## Summary

In markups module, clicking on the eye icon to set visibility OFF of an empty folder makes it disappear.
In data module, clicking on the eye icon to set visibility ON of the same folder does not make it reappear in markups module.

## Steps to reproduce

- Choose "Markups" module
- In subject hierarchy, create a folder
- Toggle folder visibility off
- Folder disappear from markups subject hierarchy

## Expected behavior

Folder is still visible in markups subject hierarchy with visibility off (closed eye). This is the behavior in data module.

## Environment
- Slicer version: Slicer-5.1.0-2022-10-17-linux-amd64
- Operating system:  Linux 5.13.0-52-generic Ubuntu 20.04.1

**Comment by cpinter** [comment] 2022-10-19 10:42
The folder only disappears when it has no children, but if it has a markups node child, it does not. This is due to the fact that the SH tree view in the Markups module is filtered to only show markups nodes and their parents. So when you hide the folder (or change its color for that matter), the proxy model runs the filter and sees that it has no markups child, so does not display it. 

It is possible that the [showEmptyHierarchyItems](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.h#L56) property in the sort filter proxy model does not work correctly, because it is supposed to not hide the empty hierarchy items when there is filtering, and it is on in the Markups module by default.

(To play with it:
```
markupsModuleWidget = slicer.modules.markups.widgetRepresentation()
activeMarkupTreeView = findChild(markupsModuleWidget, 'activeMarkupTreeView')
activeMarkupTreeView.sortFilterProxyModel().showEmptyHierarchyItems = False
```
)

It is also not very consistent is the time the filtering is run. For example when you rename the folder, the filter is not updated. Or when you create the folder in the first place, but I think it is better this way because it gives the user the chance to actually create new folders from within Markups.

**Comment by jamesobutler** [comment] 2022-12-22 21:12
Another user has commented about this behavior as being unexpected. See https://discourse.slicer.org/t/markup-subject-folder-disappears-after-toggling-visibility-in-data-module/26890

**Comment by jcfr** [comment] 2023-06-20 15:12
@cpinter Would you have the bandwidth to help address this ?

**Comment by cpinter** [comment] 2023-07-10 11:25
I'm waiting for feedback to the question raised just above. To me there is no obvious way to fix this so a consensus is needed. Thank you!

**Comment by jamesobutler** [comment] 2023-07-10 11:34
I was thinking about this recently and was thinking that we should maybe consider folders as containers that are always shown and not as node objects to filter. If a user has created a subject hierarchy with various folders and then goes into the Markups module to add markups into specific folders they are unable to do so. Therefore I think the subject hierarchy should not filter out folders which would also avoid this issue of toggling the visibility of the folder resulting in the folder making it disappear.

**Comment by lassoan** [comment] 2023-07-10 13:30
In the "Scene collection" in Blender (= subject hierachy in Slicer), empty collections (= folders in Slicer) are shown when filtering is used. For example, if you choose to not show meshes and there is a folder that only contains meshes then the folder is still displayed, it just appears empty. This is the behavior that @jamesobutler described above.

Interestingly, when you search in the tree (which is also kind of filtering, as it only shows items that have the specified string in their name) then empty folders are hidden.

So, probably we need to be able to show/hide empty folders. We just need to figure out how to switch between the two behaviors. It could be fully automatic (e.g., hide when searching, show when filtering based in node type) or it could be manual (e.g., allow the user to choose the behavior in the context menu; maybe with some automation such as enabling "show empty folders" when adding a new folder).

**Comment by cpinter** [comment] 2023-07-11 10:05
Thanks for the input!

It seems like an acceptable change to not filter out empty folders, especially that folders are typically created by the user so they would want to use them. It is good to know that other software works that way as well. A proposition:

* By default the proxy model accepts all `Folder` type items
* If the `nameFilter` is not empty, which happens if the user is filtering manually by entering a string, the empty folders are not shown. This would be the same as the current behavior (i.e. only show containers if they are parents of accepted items)
* The subject and study container items would still be filtered out. These are populated by DICOM and to me it does not seem useful to show "empty" subject or study if none of their children are accepted. It makes complete sense to organize data into manually created folders, but moving data between patients or studies is not typical

I think this would be a fairly simple change, both in usability and in implementation.

**Comment by lassoan** [comment] 2023-07-11 11:29
> * moving data between patients or studies is not typical

I agree it is not typical, but it is a valid need. It would be also quite unexpected that some kind of folders disappear while others don't.

It would be an acceptable default behavior if it could be changed (e.g., by having a "Show empty subject/study folders" option in the context menu). It could be automatically enabled if you create a subject folder to ensure that the error reported in this issue does not occur (i.e., you create a folder that later disappears).

I think the "Show empty folders" option (appearing when there is non-name-based filtering) would be simpler and cleaner than the  "Show empty subject/study folders" option.

Is we want to implement something without adding a new option for the user: we could show all the empty folders but make them gray, therefore much easier to visually ignore.

**Comment by cpinter** [comment] 2023-07-11 12:18
> I agree it is not typical, but it is a valid need

We want to allow showing empty folders in the markups tree view (and now talking about all SH tree views), because it is very typical that the user wants to create a folder and then add items to it afterwards. However, it is not typical that the user wants to add a subject manually from within the Markups module, or that they must move items between subjects there. If they want to do it, the Data module has no default filtering, so it is possible to do it there.

However, it is not that bad showing empty subjects/studies.

> but make them gray, therefore much easier to visually ignore

I don't remember having seen any way to do this from the proxy model. Do you have a concrete idea?

**Comment by lassoan** [comment] 2023-07-11 12:45
> I don't remember having seen any way to do this from the proxy model. Do you have a concrete idea?

Maybe we could have some item properties to indicate that the item should be "suppressed" and use that for coloring in the view?

**Comment by jcfr** [comment] 2023-07-25 14:52
Proposed path forward:
* Review behavior of [showEmptyHierarchyItems](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.h#L56) discussed in https://github.com/Slicer/Slicer/issues/6596#issuecomment-1283799232
* When creating a new folder (empty by definition), toggle the option `Show Empty Folder` to `on`. This means `(1)` and `(2)` illustrated below would be visible
* On right-click, a new option `Show Empty Folder` would allow to toggle back to `off`


| Markups Right Click | Example of folder |
|--|--|
| ![image](https://github.com/Slicer/Slicer/assets/219043/be59ce7e-93b2-4a1c-9a9b-4378089dde4a) | ![image](https://github.com/Slicer/Slicer/assets/219043/49bc7da2-24c7-4ca0-8564-7f17c85cb480) |

**Comment by cpinter** [comment] 2023-08-10 10:56
Great, sounds good. I'll be working around SH plugins in the core so I'll do this in a separate branch.

**Comment by cpinter** [comment] 2023-08-10 12:24
After thinking about this a few questions:

* The new folder is added by an SH plugin, which can manage the MRML scene (and thus the SH node content), but it does not have access to the view. The [showEmptyHierarchyItems](https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSortFilterSubjectHierarchyProxyModel.h#L56) property on the other hand, is in the SH proxy model, which is [created by each view](https://github.com/Slicer/Slicer/blob/3f64c3780139447be3b0f2bbee3896dd3716ac54/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx#L208-L209). So the SH plugin has no way to access specific views and proxy models. Should the SH plugin turn this property on for all the views? For example we could use a mechanism similar to [requestExpandItem](https://github.com/Slicer/Slicer/blob/3f64c3780139447be3b0f2bbee3896dd3716ac54/Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx#L203)
* Should the new option `Show empty folder` (sentence case because it is used overwhelmingly at least in SH) only appear after the automatic change described above?

**Comment by lassoan** [comment] 2023-08-12 10:37
Could the proxy model be changed in the callback function of the right-click menu action?

**Comment by cpinter** [comment] 2023-08-14 13:01
What do you mean changed? Can you please elaborate a bit?

The problem is that there is no "the" proxy model, but one for each view, and this could only be handled on the view level, which I'd be hesitant to do.

**Comment by cpinter** [comment] 2023-08-29 15:24
I implemented the change as I understood the requirements, see this video:

https://github.com/Slicer/Slicer/assets/1325980/820770a2-494c-4025-b13f-2994a83477de

It has been bothering me for a while that the expand to level function was in the tree view and not a plugin. Now that we have access to the tree view from the plugins it has become possible so I'd like to do it and then make the PR if that's alright with everyone.

**Comment by cpinter** [comment] 2023-08-29 15:27
Note that creating subjects and studies do not trigger the changes (enabling the showEmptyHierarchyItems property and showing the new action), only creating folders. I don't have a strong opinion on whether it should or not, but it seems to me that patients and studies usually are populated automatically when loading DICOM data, and also in the UI we talk about "folders" not "hierarchy items", so things might be cleaner this way.

**Comment by lassoan** [comment] 2023-08-29 19:19
Patients and studies are folders (subtype of folder). Why are you considering not triggering the changes?

**Comment by cpinter** [comment] 2023-08-30 13:30
I am not considering it, it's just that the folder plugin is not the owner of those folder types and thus this is a question that needs to be considered explicitly (I think it's called the DICOM SH plugin). It is true that toggling the checkbox that appears after creating a folder has an effect on subject/study as well. To you it seems straightforward that they are included equally in this new mechanism? In that case I can add the related code to the DICOM plugin as well.

**Comment by cpinter** [comment] 2023-09-04 12:31
Can you please confirm that you'd like me to add the same feature to the DICOM plugin for subjects and studies?

**Comment by cpinter** [comment] 2023-09-04 13:16
I made the pull request. Please review and let me know. Thanks!

**Comment by cpinter** [comment] 2023-09-12 13:18
There's a video above, please watch and let me know if that's OK. The DICOM subject and study work the same way now. Thanks!

**Comment by cpinter** [comment] 2023-09-18 09:21
I did the fix two weeks ago. The video shows how the feature works. Can someone please take a look?

**Comment by cpinter** [comment] 2023-09-19 18:00
Related PR has been merged. This can be tested in tomorrow's preview.

**Comment by cpinter** [comment] 2023-11-15 14:48
Can we close this issue?

**Closed** 2023-11-15 14:56 UTC
Labels: Type: Bug

**Comment by cpinter** [comment] 2023-11-15 15:14
Great, thanks!
