### ISSUE TITLE
simpleITK cannot find python_d.lib，I find python only configured release mode ，no debug

### ISSUE THREAD

**Issue by arthurx70** [Slicer/Slicer#4994] opened 2020-06-19 02:06 UTC
[Give a short summary of what the problem is]

## Steps to reproduce

[describe what you did and what happened - attach screenshots if possible]

## Expected behavior

[describe what you expected to happen]

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

**Comment by arthurx70** [comment] 2020-06-19 02:09
python.lib can generated，the debug one cannot

**Comment by lassoan** [comment] 2020-06-20 01:49
Thanks @jamesobutler I agree that this looks like a duplicate of https://github.com/Slicer/Slicer/issues/4991, so I'm closing this one.

**Closed by lassoan** 2020-06-20 01:49 UTC
Labels: type:bug
