### ISSUE TITLE
Slicer release 5.0.3 documentation links are broken

### ISSUE THREAD

**Issue by HarryDC** [Slicer/Slicer#6500] opened 2022-08-12 13:10 UTC
## Summary

When clicking on the "online documentation" link in the help box the resulting webpage is a "file not found" 

## Steps to reproduce

Open a module, open "Help and Acknowledgment", Click on "online documentation"

## Expected behavior

Link should open on a valid documentation page

## Environment
- Slicer version: Slicer-5.0.3 r30893
- Operating system: Windows 

## Triage

it looks like the 5.0 documentation links are `https://slicer.readthedocs.io/en/5.0/user_guide/modules/transforms.html`  `5.0` being the correct path, whereas the link that slicer tries to access is `https://slicer.readthedocs.io/en/v5.0/user_guide/modules/transforms.html` `v5.0` seems to be the incorrect path

**Comment by pieper** [comment] 2022-08-12 13:44
🙏 thanks for the report.  I confirm this happens for me to.

**Comment by jcfr** [comment] 2022-08-12 13:54
Considering that the documentation URLs associated with releases are generated using the following:

`qSlicerCoreApplication::documentationVersion`:

https://github.com/Slicer/Slicer/blob/v5.0.3/Base/QTCore/qSlicerCoreApplication.cxx#L2189-L2197

`qSlicerCoreApplication::documentationBaseUrl()`:

https://github.com/Slicer/Slicer/blob/v5.0.3/Base/QTCore/qSlicerCoreApplication.cxx#L2171-L2186 


This explained what we observed.

**Comment by HarryDC** [comment] 2022-08-12 20:28
A easy fix for this release could be to set up the appropriate read the docs folder with a ‘v5.0’ tag in the repository

**Comment by jcfr** [comment] 2022-08-12 22:26
Few weeks ago, we concluded that maintenance branch would be named like `X.Y` (similarly to what we have in the extension index).

To address this, I added a redirect from `v5.0` to `5.0`

![image](https://user-images.githubusercontent.com/219043/184452389-2f3300bd-a916-4611-82ec-d3a5a8dd257b.png)

See also https://docs.readthedocs.io/en/stable/user-defined-redirects.html#redirecting-a-whole-sub-path-to-a-different-one

**Comment by jcfr** [comment] 2022-08-16 18:45
To follow up on this, it turns out the redirect doesn't work if the link only include `v5.0` without the `/` at the end.

This is now described in a readthedocs issue. See https://github.com/readthedocs/readthedocs.org/issues/9507

| from URL | to URL | Status |
|--|--|--|
| https://slicer.readthedocs.io/en/v5.0  | https://slicer.readthedocs.io/en/5.0 | :x: |
| https://slicer.readthedocs.io/en/v5.0/  | https://slicer.readthedocs.io/en/5.0/ | :heavy_check_mark:  |
| https://slicer.readthedocs.io/en/v5.0/user_guide/modules/transforms.html  | https://slicer.readthedocs.io/en/5.0/user_guide/modules/transforms.html | :heavy_check_mark:  |

**Comment by jcfr** [comment] 2022-08-16 20:17
Previous attempt doesn't work as expected

**Comment by jcfr** [comment] 2022-08-16 21:40
Closing. After clearing the cache, the integrated works as expected.

![image](https://user-images.githubusercontent.com/219043/184990197-98cb2e51-623d-44cc-a7f6-0ae6d361404a.png)

**Closed by jcfr** 2022-08-16 21:40 UTC
Labels: type:bug

**Comment by pieper** [comment] 2022-08-17 16:50
Thanks Jc!  Confirmed it works for me.
