### ISSUE TITLE
To run Slicer 

### ISSUE THREAD

**Issue by reena4jan** [Slicer/Slicer#6093] opened 2021-12-24 13:09 UTC
How to set this i am not understand this part

Run CMake (cmake-gui) from the Windows Start menu
Set Where is the source code to <Slicer_SOURCE> location
Set Where to build the binaries to <Slicer_BUILD> location. Do not configure yet!
 Qt5_DIR variable pointing to Qt5 folder: click Add entry button, set Name to Qt5_DIR, set Type to PATH, and set Value to the Qt5 folder, such as C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5.
Click Configure

I tried but not able...Please let me know

**Comment by reena4jan** [comment] 2021-12-25 04:25
I am not resolve this issue...Please let me know

CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
The C compiler identification is MSVC 19.29.30136.0
The CXX compiler identification is MSVC 19.29.30136.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error: File /Source/cmConfigure.cmake.h.in does not exist.
CMake Error at CMakeLists.txt:54 (configure_file):
  configure_file Problem configuring file


CMake Error: File /Source/cmVersionConfig.h.in does not exist.
CMake Error at CMakeLists.txt:58 (configure_file):
  configure_file Problem configuring file


CMake Error: File /Source/CPack/cmCPackConfigure.h.in does not exist.
CMake Error at CMakeLists.txt:62 (configure_file):
  configure_file Problem configuring file


CMake Error: File /Source/CMakeSourceDir.txt.in does not exist.
CMake Error at CMakeLists.txt:68 (configure_file):
  configure_file Problem configuring file


CMake Error at CMakeLists.txt:1217 (CMake_OPTIONAL_COMPONENT):
  Unknown CMake command "CMake_OPTIONAL_COMPONENT".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring incomplete, errors occurred!
See also "C:/D/S4D/CMakeFiles/CMakeOutput.log".

**Comment by lassoan** [comment] 2022-02-17 01:51
Many developers build Slicer every day without issues, so the problem is most likely not in Slicer but in the documentation not clear enough or something wrong in the user's environment. Such issues are resolved via the Slicer forum. Closing the issue here - @reena4jan please post on the [Slicer forum](https://discourse.slicer.org/) if you still have trouble with this.

**Closed by lassoan** 2022-02-17 01:51 UTC
