### ISSUE TITLE
Harden transform is applied for volume rendering but not for scan

### ISSUE THREAD

**Issue by feliciamiranda** [Slicer/Slicer#6664] opened 2022-11-14 19:41 UTC
@allemangD 
## Summary
After loading a CBCT scan, and altering the head position using the Transforms tool and Harden transform, the volume rendering “displays” the new position, but the original scan does not receive the exact same position even in the reformat option. This is an issue for the sequence of image processing steps (segmentation, registration, landmark identification). Figure below.

## Steps to reproduce

- Load an original  CBCT scan in Slicer  (Figure 1)
- Obtain a 3D view using the Volume Rendering tool
- Go to transform tool, create a new linear transform
- Change the scan from the transformable to the transformed box
- Do the required changes
- Click on Harden Transform 
- Save the scan file
- Close the Scene and upload the saved scan
- Obtain a 3D view using the Volume Rendering tool: now the volume rendering shows the changed position, but the scan does not show the same position in the reformat option (Figure 2) ; if we select axial/coronal/sagittal views the orientation improves (Figure 3 ) but is not exactly the same as if we use the Apply matrix module of CMFreg (FIgure 4) . Figure 5 shows the overlay of the image from figure 3 and 4.

![Fig1](https://user-images.githubusercontent.com/110692943/201750451-594fdfc4-888a-4b2f-af7e-8ce087a6a62e.png)

![Fig2](https://user-images.githubusercontent.com/110692943/201750466-4e351407-dfb8-42d7-8a86-dc0f67c0f158.png)

![Fig3](https://user-images.githubusercontent.com/110692943/201750481-8c75b865-ec04-4703-bc71-4ad49c2a18c0.png)

![Fig4](https://user-images.githubusercontent.com/110692943/201750497-0878790a-69dc-4b7a-95a0-8ffcc35a2ac8.png)

![Fig5](https://user-images.githubusercontent.com/110692943/201750516-2f27083b-5186-452f-a793-ef655553c086.png)

*I can provide data to the test if needed.

## Expected behavior

It would be expected that both the CBCT scan and volume rendering show the final head oriented position (Figure 4). 

## Environment
- Slicer version: Slicer-5.1.0-2022-10-27
- Operating system: Windows and Mac

**Comment by lassoan** [comment] 2022-11-14 21:35
It looks like a duplicate of https://github.com/Slicer/Slicer/issues/6648

**Comment by lassoan** [comment] 2023-06-20 16:22
Since there was no feedback, assuming it is a duplicate and closing this issue.

**Closed by lassoan** 2023-06-20 16:22 UTC
Labels: type:bug
