### ISSUE TITLE
Module Panel cannot be hidden when switching to extension module

### ISSUE THREAD

**Issue by nnzzll** [Slicer/Slicer#6518] opened 2022-09-01 02:28 UTC
## Summary

I'm developing a extension module and I'd like to hide the module panel when switching to my extension module, however, whatever I do the module panel always exists. 

## Steps to reproduce

I‘m working on loadable module but the scripted module gives the same result.
So, to make it easy to reproduce, I will use scripted module as an example.

1. Create a extension using extension wizard and add a new scripted module into it.
2. Modify the `enter()` method with code below
```.py
  def enter(self):
    """
    Called each time the user opens this module.
    """
    # Make sure parameter node exists and observed
    self.initializeParameterNode()
    moduleDock = slicer.util.mainWindow().findChild("QDockWidget", "PanelDockWidget")
    print(moduleDock) # this line prints the QDockWidget's address and object name
    moduleDock.setVisible(False) # this line didn't work
```

## Expected behavior

Hide the module panel when switching to this module. But the module panel is still visible.

## Environment
- Slicer version: Slicer-4.13.0-2022-03-09
- Operating system: Windows 10 & Ubuntu 18.04

**Comment by jamesobutler** [comment] 2022-09-01 03:01
In what way are you showing your module if you’re planning to hide the panel that typically shows the current Slicer module?

**Comment by nnzzll** [comment] 2022-09-01 06:47
> In what way are you showing your module if you’re planning to hide the panel that typically shows the current Slicer module?

I add my moduleWidget to a `qSlicerSingletonViewFactory` object and register this View to `layoutManager`. Calling `setLayout` method of `layoutManager` can show my moduleWidget

**Comment by lassoan** [comment] 2022-09-01 21:49
The application makes the module panel visible if you switch to a module. So, probably you have set the module panel visibility too early. If you set up a QTimer with 0 timeout and hide the module panel in the callback then that will be executed after the module switch has completed. But it is probably simpler to just use that left panel for displaying something and then you don't need to hide it. You can hide the Slicer logo (or you can replace it with your own).

I'll close this issue, because these kind of discussions belong to the Slicer forum (Development category). The issue is for tracking issues and planned features for Slicer core.

**Closed by lassoan** 2022-09-01 21:49 UTC
Labels: type:bug
