### ISSUE TITLE
Default load type of normal NRRD volumes is Segmentation if reader registered too early

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#6553] opened 2022-09-27 09:53 UTC
## Summary

If a module is added that is loaded too early (its name starts at the beginning of the alphabet) and depends on the Segmentations module, the segmentation reader is registered before the volume one, and normal (without `.seg`) NRRD files are offered to load by default as segmentation nodes. This then causes an unexpected view of the loaded volume, but worse, it may take so long (converting the basically noise image to closed surface) that the user needs to close the application.

A possible solution as discussed with @lassoan could be for the readers to return confidence values and decide the optimal reading type based on that instead of the order of readers after a simple yes/no evaluation.

## Steps to reproduce

* Save this file https://gist.github.com/cpinter/0f0502d15e0572e7f0cdaaddd26b0e41
* Add it to Additional module paths
* Restart Slicer
* Try to load any NRRD (e.g. save the MRHead sample volume to NRRD)
* The default reading type will be Segmentation instead of volume

## Expected behavior

Volumes not containing the special extension `.seg.nrrd` are loaded as volumes not segmentations.

## Environment
- Slicer version: Slicer-5.1.0-2022-09-20
- Operating system: Windows 10

**Comment by jcfr** [comment] 2023-06-20 15:17
@lassoan Was this addressed following the integration of this pull request ?
*  https://github.com/Slicer/Slicer/pull/6998

**Comment by lassoan** [comment] 2023-06-20 15:21
Yes, the issue is fixed by #6998

**Closed by lassoan** 2023-06-20 15:21 UTC
Labels: type:bug
