### ISSUE TITLE
Export DICOM from 3D slicer

### ISSUE THREAD

**Issue by zaimoh** [Slicer/Slicer#6319] opened 2022-04-19 16:43 UTC
[Give a short summary of what the problem is. Note: Before submitting an error report, please test if the problem is reproducible in the latest Slicer Preview Release. If the problem does not occur in the latest Slicer Preview Release then most likely it has been already fixed and there is no need to report it again.]

## Steps to reproduce

[describe what you did and what happened - attach screenshots if possible]

## Expected behavior

[describe what you expected to happen]

## Environment
- Slicer version: Slicer-4.??.?-YYYY-MM-DD
- Operating system: Windows / Linux / Mac + which version

**Comment by cpinter** [comment] 2022-04-19 20:07
This seems an accidental empty duplicate of #6320 , closing.

**Closed by cpinter** 2022-04-19 20:07 UTC
Labels: type:bug
