### ISSUE TITLE
Splash screen cannot be removed by clicking it

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#7280] opened 2023-10-12 20:05 UTC
After slicermorph install, instantiating the modules takes a long time (this is related to itk libraries for ALPACA), sometimes as much as a minute after cold restarts. This is not a big deal, except the splash screen stays in the middle of the desktop and cannot be moved or  cannot be hidden by clicking it. It interferes with the user's ability to interact and work on the desktop, since the Slicer splash window is in the middle of the screen.

Either allow to hide the splash screen by clicking on it (which used to be possible), or somehow allow it to be repositioned. 
@jcfr

**Comment by lassoan** [comment] 2023-10-12 20:11
Are you sure it is just import? That should not take more than a few seconds. Maybe some module attempts to install a Python package at startup? (that should never be done, `pip_install` should be done as late as possible, when the user requested an operation that requires installation of a package).

Search for `pip_install` in the source code of all modules and make sure they are only called right before the package is actually needed.

**Comment by muratmaga** [comment] 2023-10-12 23:00
The only pip_install we do is when people switch to alpaca first time. I will double check but @jcfr warned us about this long module instantiation during the itk re-implement of alpaca functions. So I assumed it is related. It just became for some reason a bit more long than it was (compared to 5.2.2). So the splash screen issue became more noticeable.

**Comment by jcfr** [comment] 2023-10-26 17:09
> re: import

The `MorphoSourceImport` module is installing & importing `pandas` at startup time[^1].

[^1]: https://github.com/SlicerMorph/SlicerMorph/blob/b1abc655d8de0ced9734d66e7390785700c350fc/MorphoSourceImport/MorphoSourceImport.py#L30-L34

This should be fixed in:
* https://github.com/SlicerMorph/SlicerMorph/pull/284

**Comment by jcfr** [comment] 2023-10-26 17:11
> re: instantiating the modules takes a long time 

After selecting the ALPACA module the following is displayed:

<img width=50% src="https://github.com/Slicer/Slicer/assets/219043/b93c3e2e-8efb-406b-8ae8-40ea77e3ee7d"/>

**Comment by jcfr** [comment] 2023-10-26 21:30
> re: instantiating the modules takes a long time

On subsequent restart of the application, "instantiating" the Alpaca module is indeed taking time.

This is due to the fact we import "itk" when the module id being discovered[^1]. This was initially done to avoid the user to wait after the application has been started.

This should be fixed in:
* https://github.com/SlicerMorph/SlicerMorph/pull/285

[^1]: https://github.com/SlicerMorph/SlicerMorph/blob/c74b011b2c904f7bb1f6f78a03c9338b4a8afde4/ALPACA/ALPACA.py#L24-L45

**Comment by jcfr** [comment] 2023-10-26 21:37
_Originally posted by @muratmaga in https://github.com/Slicer/Slicer/issues/7280#issue-1940714371_

> After slicermorph install, instantiating the modules takes a long time (this is related to itk libraries for ALPACA), sometimes as much as a minute after cold restarts. This is not a big deal, except the splash screen stays in the middle of the desktop and cannot be moved or  cannot be hidden by clicking it. It interferes with the user's ability to interact and work on the desktop, since the Slicer splash window is in the middle of the screen.

The progress dialog is not modal should not prevent the user from switching and using other applications.

**Comment by jcfr** [comment] 2023-10-26 21:40
Considering the issue is being addressed in the upstream project and that this will allow the splashscreen to be displayed only few seconds during application startup, I am now closing this issue.

**Closed by jcfr** 2023-10-26 21:40 UTC
Labels: type:bug, status:invalid
