### ISSUE TITLE
Script repo default snippet fails:  loadSegmentation and OverwriteNone don't play together

### ISSUE THREAD

**Issue by fusentasticus** [Slicer/Slicer#5288] opened 2020-11-01 22:24 UTC
In [the script repo](https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository), which I keep under my pillow now,  the advice for taming the segment editor is:
```
defaultSegmentEditorNode = slicer.vtkMRMLSegmentEditorNode()
defaultSegmentEditorNode.SetOverwriteMode(slicer.vtkMRMLSegmentEditorNode.OverwriteNone)
slicer.mrmlScene.AddDefaultNode(defaultSegmentEditorNode)
```
but that does not work if `slicer.util.loadSegmentation` is called before the Segment Editor module is actually used.
## Steps to reproduce
- Add the three lines to .slicerrc.py
- Do a slicer.util.loadSegmentation invocation from console for some previously saved segmentation on disk
- Choose the Segment Editor module, a master volume, and activate Paint

## Expected behavior
- Then "Modify other segments" is still in `Overwrite all` mode, not in `OverwriteNone` mode (Allow overlap)
- To change that programmatically at this point, I do 
```
default_segment_editor_node = [n for n in  slicer.mrmlScene.GetNodesByClass("vtkMRMLSegmentEditorNode")][0]
default_segment_editor_node.SetOverwriteMode(slicer.vtkMRMLSegmentEditorNode.OverwriteNone)
```
- Also, I verify that `id(defaultSegmentEditorNode)` and `id(default_segment_editor_node)` are different, and that puzzles me.

I should mention that I'm invocating Slicer through a Jupyter note book - and I think that this worked before I updated to the release version from a pre-release 4.11 version.

## Environment
- Slicer version: 4.11.20200930 r29402 / 002be18
- Operating system: Linux Ubuntu 20.04

**Comment by fusentasticus** [comment] 2020-11-02 16:05
To simplify: the three line snippet from the script repo (to prevent segment overwriting) doesn't work either if simply doing as follows:
- put the three lines in the .slicerrc.py file (or execute them in the console after start)
- start Slicer as `~/Software/Slicer-4.11.20200930-linux-amd64/Slicer`
- and then load the sample MRhead, choose Segment Editor, make new segment ("+"), select Paint mode -- the "Modify other segments" still shows "Overwrite all".  
- execute the two alternative lines I gave above, and the mode is showed as "Allow overlap"

My problem is that those two lines don't work in .slicerrc.py (before the module is actually used) and I don't know how to activate the Segment Editor programmatically.

**Comment by fusentasticus** [comment] 2020-11-02 20:38
I did find a work-around - for inclusion in `.slicerrc.py`. So perhaps it's just the code snippet in the script repo that's wrong? If so, please close ticket.
```
# Allow segments to overlap each other by default
slicer.util.selectModule("SegmentEditor")
defaultSegmentEditorNode = slicer.modules.SegmentEditorWidget.editor.mrmlSegmentEditorNode()
defaultSegmentEditorNode.SetOverwriteMode(slicer.vtkMRMLSegmentEditorNode.OverwriteNone)
slicer.util.selectModule("Welcome")
```

**Comment by lassoan** [comment] 2020-11-02 21:50
The root cause of the issue was fixed in https://github.com/Slicer/Slicer/commit/49bcde1522c065a07c90da65d5b2737d88fc12b5 but it is not yet available in latest stable release.

**Closed by lassoan** 2020-11-02 21:50 UTC
Labels: type:bug
